layout_spectrum: 0.92197
favicon: null
name: EsSentir
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.3721805
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 0.75
  brandColors:
    - '#000000'
    - '#BE2127'
    - '#0C70B4'
    - '#18164A'
    - '#A4238E'
typography_spectrum: 0.38825
